spring:
  application:
    name: wab
  datasource:
    url: jdbc:postgresql://localhost:5432/myun_store
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
        order_updates: true
    open-in-view: false
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
image:
  upload:
    dir: "${UPLOAD_DIR:./product-images}"
lock:
  time:
    duration: 5 #Time in minutes
