spring:
  application:
    name: wab
  datasource:
    url: jdbc:postgresql://localhost:5432/myun_store
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    open-in-view: false
image:
  upload:
    dir: ""
