INSERT INTO product_brand (name,
                           description,
                           image_path)
VALUES ('Gucci', 'Gucci', 'gucci_1.png'),
       ('Prada', 'Prada', 'prada_2.jpg'),
       ('Louis Vuitton', 'Louis Vuitton', 'Louis_Vuitton_3.jpg'),
       ('Adidas', 'Adidas', 'adidas_4.jpg'),
       ('Nike', 'Nike', 'Nike_5.jpg'),
       ('Chanel', 'Chanel', 'Chanel_Classic_Flap_Bag_6.jpg'),
       ('Prada', 'Prada', 'Prada_Nylon_Bag_7.jpg'),
       ('Hermes', 'Hermes', 'Hermes_Birkin_8.jpg'),
       ('Dior', 'Dior', 'Dior_Lady_Dior_9.jpg'),
       ('Michael Kors', 'Michael Kors', 'Michael_Kors_10.jpg'),
       ('Balenciaga', 'Balenciaga', 'Balenciaga_Hourglas_11.jpg'),
       ('Bottega Veneta', 'Bottega Veneta', 'Bottega_Veneta_Pouc_12.jpg'),
       ('Yves Saint Laurent', 'Yves Saint Laurent', 'Yves_Saint_Laurent_Lou_Camera_Ba_13.jpg'),
       ('Versace', 'Versace', 'Versace_Virtu_14.jpg');
