INSERT INTO product (name,
                     description,
                     price,
                     product_brand_id,
                     image_path)
VALUES ('Gucci', 'Stylish womens handbag', 8075.99, 1, 'gucci_1.png'),
       ('Prada', 'Elegant womens handbag', 7092.99, 2, 'prada_2.jpg'),
       ('Louis Vuitton', 'Exclusive womens handbag', 1799.99, 3, 'Louis_Vuitton_3.jpg'),
       ('Adidas', 'Exclusive womens handbag', 666.99, 4, 'adidas_4.jpg'),
       ('Nike', 'Exclusive womens handbag', 777.99, 5, 'Nike_5.jpg'),
       ('Chanel Classic Flap Bag', 'Iconic chain handbag', 799.99, 6, 'Chanel_Classic_Flap_Bag_6.jpg'),
       ('Polo Ralph Lauren', 'Trendy nylon handbag', 3999.99, 7, 'Ralph_Lauren_7.jpg'),
       ('Hermes Birkin', 'Luxury leather handbag', 12500.00, 8, 'Hermes_Birkin_8.jpg'),
       ('Dior Lady Dior', 'Sophisticated embroidered handbag', 4500.00, 9, 'Dior_Lady_Dior_9.jpg'),
       ('Michael Kors Jet Set', 'Modern travel tote', 2490.99, 10, 'Michael_Kors_10.jpg'),
       ('Balenciaga Hourglass', 'Avant-garde hourglass-shaped handbag', 1499.99, 11, 'Balenciaga_Hourglas_11.jpg'),
       ('Bottega Veneta Pouch', 'Minimalist clutch', 8991.99, 12, 'Bottega_Veneta_Pouc_12.jpg'),
       ('Yves Saint Laurent Lou Camera Bag', 'Stylish everyday handbag', 6199.99, 13,
        'Yves_Saint_Laurent_Lou_Camera_Ba_13.jpg'),
       ('Versace Virtus', 'Bold handbag with gold accents', 1299.99, 14, 'Versace_Virtu_14.jpg'),
       ('Gucci Soho Disco Bag Review', 'Compact and stylish crossbody bag', 8500.99, 1, 'gucci_15.jpg'),
       ('Prada Cleo Bag', 'Sleek and modern shoulder bag', 7450.99, 2, 'Prada_17.jpg'),
       ('Louis Vuitton Neverfull', 'Spacious everyday tote bag', 2100.99, 3, 'Louis_Vuitton_18.jpg'),
       ('Adidas Originals Tote', 'Casual tote bag with Adidas logo', 699.99, 4, 'Adidas_19.jpg'),
       ('Chanel Boy Bag', 'Classic handbag with quilted design', 820.99, 6, 'Chanel_20.jpg'),
       ('Nike Gym Bag', 'Compact and functional gym bag', 800.99, 5, 'Nike_21.jpg'),
       ('Hermes Kelly', 'Legendary leather handbag', 13000.00, 8, 'Hermes_22.jpg'),
       ('Dior Saddle Bag', 'Iconic saddle-shaped handbag', 4600.00, 9, 'Dior_23.jpg'),
       ('Michael Kors Mercer', 'Stylish leather tote', 2550.99, 10, 'Michael_Kors_24.jpg'),
       ('Balenciaga City Bag', 'Iconic leather handbag', 1550.99, 11, 'Balenciaga_25.jpg'),
       ('Bottega Veneta Jodie', 'Minimalist and luxurious handbag', 9100.99, 12, 'Bottega_26.jpg'),
       ('Saint Laurent College Bag', 'Luxurious and stylish handbag', 6499.99, 13, 'Saint_Laurent_27.jpg'),
       ('Versace Medusa Tote', 'Fashion-forward tote with Medusa logo', 1399.99, 14, 'Versace_28.jpg'),
       ('Ralph Lauren Emerie Shopper', 'Stylish and durable tote bag''', 6350.99, 7, 'Ralph_Lauren_29.jpg');
