INSERT INTO product (name,
                     description,
                     price,
                     product_brand_id,
                     image_path)
VALUES ('Gucci', 'Stylish womens handbag', 8075.99, 1, 'gucci_1.png'),
       ('Prada', 'Elegant womens handbag', 7092.99, 2, 'prada_2.jpg'),
       ('Louis Vuitton', 'Exclusive womens handbag', 1799.99, 3, 'Louis_Vuitton_3.jpg'),
       ('Adidas', 'Exclusive womens handbag', 666.99, 4, 'adidas_4.jpg'),
       ('Nike', 'Exclusive womens handbag', 777.99, 5, 'Nike_5.jpg'),
       ('Chanel Classic Flap Bag', 'Iconic chain handbag', 799.99, 6, 'Chanel_Classic_Flap_Bag_6.jpg'),
       ('Prada Nylon Bag', 'Trendy nylon handbag', 3999.99, 7, 'Prada_Nylon_Bag_7.jpg'),
       ('Hermes Birkin', 'Luxury leather handbag', 12500.00, 8, 'Hermes_Birkin_8.jpg'),
       ('Dior Lady Dior', 'Sophisticated embroidered handbag', 4500.00, 9, 'Dior_Lady_Dior_9.jpg'),
       ('Michael Kors Jet Set', 'Modern travel tote', 2490.99, 10, 'Michael_Kors_10.jpg'),
       ('Balenciaga Hourglass', 'Avant-garde hourglass-shaped handbag', 1499.99, 11, 'Balenciaga_Hourglas_11.jpg'),
       ('Bottega Veneta Pouch', 'Minimalist clutch', 8991.99, 12, 'Bottega_Veneta_Pouc_12.jpg'),
       ('Yves Saint Laurent Lou Camera Bag', 'Stylish everyday handbag', 6199.99, 13, 'Yves_Saint_Laurent_Lou_Camera_Ba_13.jpg'),
       ('Versace Virtus', 'Bold handbag with gold accents', 1299.99, 14, 'Versace_Virtu_14.jpg');
