INSERT INTO products (name, description, price, brand,image_path) VALUES
                                                                      ('Gucci', 'Stylish womens handbag', 8075.99, 'Gucci','gucci_1.png'),
                                                                      ('Prada', 'Elegant womens handbag', 7092.99 , 'Prada','prada_2.jpg'),
                                                                      ('Louis Vuitton', 'Exclusive womens handbag', 1799.99, 'Louis Vuitton','Louis_Vuitton_3.jpg'),
                                                                      ('Adidas', 'Exclusive womens handbag', 666.99, 'Adidas','adidas_4.jpg'),
                                                                      ('Nike', 'Exclusive womens handbag', 777.99, 'Nike','Nike_5.jpg'),
                                                                      ('Chanel Classic Flap Bag', 'Iconic chain handbag', 799.99, 'Chanel','Chanel_Classic_Flap_Bag_6.jpg'),
                                                                      ('Prada Nylon Bag', 'Trendy nylon handbag', 3999.99, 'Prada','Prada_Nylon_Bag_7.jpg'),
                                                                      ('Hermes Birkin', 'Luxury leather handbag', 12500.00, 'Hermes','Hermes_Birkin_8.jpg'),
                                                                      ('Dior Lady Dior', 'Sophisticated embroidered handbag', 4500.00, 'Dior','Dior_Lady_Dior_9.jpg'),
                                                                      ('Michael Kors Jet Set', 'Modern travel tote', 2490.99, 'Michael Kors','Michael_Kors_10.jpg'),
                                                                      ('Balenciaga Hourglass', 'Avant-garde hourglass-shaped handbag', 1499.99, 'Balenciaga','Balenciaga_Hourglas_11.jpg'),
                                                                      ('Bottega Veneta Pouch', 'Minimalist clutch', 8991.99, 'Bottega Veneta','Bottega_Veneta_Pouc_12.jpg'),
                                                                      ('Yves Saint Laurent Lou Camera Bag', 'Stylish everyday handbag', 6199.99, 'Yves Saint Laurent','Yves_Saint_Laurent_Lou_Camera_Ba_13.jpg'),
                                                                      ('Versace Virtus', 'Bold handbag with gold accents', 1299.99, 'Versace','Versace_Virtu_14.jpg');
