-- INSERT INTO cart_item (id, product_id, quantity) VALUES
--                                                           (4, 2, 1),
--                                                           (5, 1, 1),
--                                                           (6, 3, 2);
